jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name goldrush_CI
    displayName: Create Anaconda environment
  - script: |
      source activate goldrush_CI
      conda install --yes -c conda-forge mamba 
      mamba install --yes -c conda-forge compilers meson gperftools libdivsufsort sdsl-lite google-sparsehash boost
      mamba install --yes -c bioconda btllib
    displayName: Install dependencies
  - script: |
      meson build
      cd build
      ninja
    displayName: Compile GoldRush
