jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name goldrush_CI
    displayName: Create Anaconda environment
  - script: |
      source activate goldrush_CI
      conda install --yes -c conda-forge mamba=1.5.10 python=3.10 
      mamba install --yes -c conda-forge -c bioconda compilers meson gperftools sdsl-lite boost-cpp sparsehash btllib libdivsufsort minimap2 tigmint ntlink miller snakemake intervaltree  
    displayName: Install dependencies
  - script: |
      source activate goldrush_CI
      meson build --prefix=$(pwd)/test_build
      cd build
      ninja install
      goldrush_path/goldrush-path --help
    displayName: Compile GoldRush
  - script: |
      source activate goldrush_CI
      export PATH=$(pwd)/test_build/bin:$PATH
      cd tests
      ./goldrush_test_demo.sh
    displayName: Test run for GoldRush


- job:
  displayName: mac-latest
  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true
  - script: |
      mkdir -p ~/miniconda3
      curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh  -o ~/miniconda3/miniconda.sh
      bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
      rm -rf ~/miniconda3/miniconda.sh
      ~/miniconda3/bin/conda init bash
      ~/miniconda3/bin/conda init zsh
      which conda
      conda --version
    displayName: Install conda
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name goldrush_CI
    displayName: Create Anaconda environment
  - script: |
      source activate goldrush_CI
      conda install --yes -c conda-forge mamba=1.5.10 python=3.10
      mamba install --yes -c conda-forge -c bioconda compilers meson gperftools sdsl-lite boost-cpp sparsehash btllib libdivsufsort minimap2 tigmint ntlink miller snakemake intervaltree 
    displayName: Install dependencies
  - script: |
      source activate goldrush_CI
      meson build --prefix=$(pwd)/test_build
      cd build
      ninja install
      goldrush_path/goldrush-path --help
    displayName: Compile GoldRush
  - script: |
      source activate goldrush_CI
      export PATH=$(pwd)/test_build/bin:$PATH
      cd tests
      ./goldrush_test_demo.sh
    displayName: Test run for GoldRush

