jobs:
- job:
  displayName: ubuntu-latest
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true
  - script: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH
  - script: conda create --yes --quiet --name goldrush_CI
    displayName: Create Anaconda environment
  - script: |
      source activate goldrush_CI
      conda install --yes -c conda-forge mamba=1.5.10 python=3.10 
      mamba install --yes -c conda-forge -c bioconda compilers meson gperftools sdsl-lite boost-cpp sparsehash btllib libdivsufsort 'minimap2>=2.21' tigmint ntlink miller snakemake intervaltree  
    displayName: Install dependencies
  - script: |
      source activate goldrush_CI
      meson build --prefix=$(pwd)/test_build
      cd build
      ninja install
      goldrush_path/goldrush-path --help
    displayName: Compile GoldRush
  - script: |
      source activate goldrush_CI
      export PATH=$(pwd)/test_build/bin:$PATH
      cd tests
      ./goldrush_test_demo.sh
    displayName: Test run for GoldRush


- job:
  displayName: mac-latest
  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: self
    persistCredentials: true
    submodules: true
  - script: |
      mkdir -p ~/miniforge3
      curl -L https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-MacOSX-x86_64.sh  -o ~/miniforge3/miniforge.sh
      bash ~/miniforge3/miniforge.sh -b -u -p ~/miniforge3
      rm -rf  ~/miniforge3/miniforge.sh
      ~/miniforge3/bin/conda init bash
      ~/miniforge3/bin/conda init zsh
      export CONDA=$(realpath ~/miniforge3/bin)
      echo "##vso[task.prependpath]$CONDA"
    displayName: Install conda
  - script: conda create --yes --quiet --name goldrush_CI
    displayName: Create Anaconda environment
  - script: |
      source activate goldrush_CI
      conda install --yes -c conda-forge mamba=1.5.10 python=3.10
      mamba install --yes -c conda-forge -c bioconda compilers meson gperftools sdsl-lite boost-cpp sparsehash btllib libdivsufsort minimap2 tigmint ntlink miller snakemake intervaltree 
    displayName: Install dependencies
  - script: |
      source activate goldrush_CI
      meson build --prefix=$(pwd)/test_build
      cd build
      ninja install
      goldrush_path/goldrush-path --help
    displayName: Compile GoldRush
  - script: |
      source activate goldrush_CI
      export PATH=$(pwd)/test_build/bin:$PATH
      cd tests
      ./goldrush_test_demo.sh
    displayName: Test run for GoldRush

