# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:

- job: linux
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - checkout: self
    submodules: true

  - script: |
      set -o errexit -o pipefail
      wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-13 main"
      sudo apt-get update
      sudo apt-get install --yes --no-install-recommends clang-format-10 clang-tidy-10 cppcheck \
        python3 python3-setuptools openjdk-16-jdk libboost-dev samtools xz-utils bzip2 lrzip
      sudo ln -sf clang-format-10 /usr/bin/clang-format
      sudo ln -sf clang-tidy-10 /usr/bin/clang-tidy
      sudo pip3 install ninja meson cmake
    displayName: 'Install required software'

  - script: meson setup build && cd build && ninja build-sdsl
    displayName: 'Build sdsl dependency'

  - script: cd build && ninja
    displayName: 'Build the project'

  - script: cd build && ninja formatcheck
    displayName: 'Run clang-format'

  - script: cd build && ninja tidycheck
    displayName: 'Run clang-tidy'

  - script: cd build && ninja cppcheck
    displayName: 'Run cppcheck'

  - script: |
      cd build && meson test --repeat=10
      if [[ $? -ne 0 ]]; then
        cat meson-logs/testlog.txt
        exit 1
      fi
    displayName: 'Run tests'

  - script: |
      set -o errexit -o pipefail
      ./compile-wrappers
      cd build && ninja test-wrappers
    displayName: 'Test ./compile-wrappers script'

- job: macos
  pool:
    vmImage: 'macOS-latest'

  steps:
  - checkout: self
    submodules: true

  - script: |
      set -o errexit -o pipefail
      brew update
      brew install llvm libomp cppcheck boost samtools coreutils xz lrzip
      brew tap adoptopenjdk/openjdk
      brew install --cask adoptopenjdk11
      sudo ln -sf $(brew --prefix llvm)/bin/clang-format /usr/local/bin/clang-format
      sudo ln -sf $(brew --prefix llvm)/bin/clang-tidy /usr/local/bin/clang-tidy
      sudo pip3 install ninja meson cmake
    displayName: 'Install required software'

  - script: meson setup build && cd build && ninja build-sdsl
    displayName: 'Build sdsl dependency'

  - script: cd build && ninja
    displayName: 'Build the project'

  - script: cd build && ninja formatcheck
    displayName: 'Run clang-format'

  - script: cd build && ninja tidycheck
    displayName: 'Run clang-tidy'

  - script: cd build && ninja cppcheck
    displayName: 'Run cppcheck'

  - script: |
      cd build && meson test --repeat=10
      if [[ $? -ne 0 ]]; then
        cat meson-logs/testlog.txt
        exit 1
      fi
    displayName: 'Run tests'

  - script: |
      set -o errexit -o pipefail
      ./compile-wrappers
      cd build && ninja test-wrappers
    displayName: 'Test ./compile-wrappers script'